In [1]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [2]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (1).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
#Declare label as last column in the source file
label=data['Purchased']
label

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [4]:
#Declaring X as all columns excluding last
X=data[['Age','EstimatedSalary']]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [5]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,label,test_size=0.3,random_state=20)
X_train, X_test, y_train, y_test

(     Age  EstimatedSalary
 268   47           144000
 108   26            86000
 21    47            49000
 231   39            42000
 33    28            44000
 ..   ...              ...
 393   60            42000
 218   46            96000
 223   60           102000
 271   59            76000
 355   60            34000
 
 [280 rows x 2 columns],      Age  EstimatedSalary
 10    26            80000
 382   44           139000
 374   37            80000
 196   30            79000
 47    27            54000
 ..   ...              ...
 147   41            30000
 375   46            32000
 113   37            55000
 291   49            89000
 172   26           118000
 
 [120 rows x 2 columns], 268    1
 108    0
 21     1
 231    0
 33     0
       ..
 393    1
 218    0
 223    1
 271    1
 355    1
 Name: Purchased, Length: 280, dtype: int64, 10     0
 382    1
 374    0
 196    0
 47     0
       ..
 147    0
 375    1
 113    0
 291    1
 172    0
 Name: Purchased, Length: 120, dtype

In [6]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [8]:

entries = len(X_train[:,0])
entries

280

In [9]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [10]:
# Sigmoid function
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [11]:
def predict(inputs,w):
    z=np.dot(inputs,w)
    return sigmoid(z)

In [12]:
def loss_func(features,labels,w):
    observations = len(labels)
    predictions = predict(features, w)
    class1_cost = -labels*np.log(predictions)
    class2_cost = (1-labels)*np.log(1-predictions)
    cost = class1_cost - class2_cost
    cost = cost.sum() / observations
    return cost

In [13]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

def update_weights(features, labels, weights, lr):    
    
    N = len(features)    
    predictions = predict(features, weights)    
    gradient = np.dot(features.T,  predictions - labels)    
    gradient /= N    
    gradient *= lr    
    weights -= gradient

    return weights

In [14]:
#Repeating the process 3000 times
cost_history = []
for i in range(3000):
    w = update_weights(X, label, w, alpha)

    #Calculate error for auditing purposes
    cost = loss_func(X, label, w)
    cost_history.append(cost)

    # Log Progress
    if i % 1000 == 0:
        print("iter: "+ str(i) + " cost: "+str(cost))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


iter: 0 cost: inf
iter: 1000 cost: inf
iter: 2000 cost: inf


In [15]:
#Print weight
w

array([ -19.43575, 1407.375  ])

In [16]:
#print bias
b

0.2

In [17]:
#predicting the label
predicted_labels=predict(X_test,w)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
#print actual and predicted values in a table
predicted_labels,label

(array([1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.29273054e-284, 1.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        8.83854139e-239, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        4.40769346e-085, 0.00000000e+000, 6.23531801e-262, 0.00000000e+000,
        1.62374994e-296, 1.00000000e+000, 1.26029000e-274, 1.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        3.42107602e-063, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 1.00000000e+000, 4.15617361e-206,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 9.35221954e-292, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00

In [19]:
# Calculating accuracy of prediction
diff = predicted_labels - y_test
acc=1.0 - (float(np.count_nonzero(diff)) / len(diff))
acc

0.5416666666666667

**Using sklearn LogisticRegression model**

In [20]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR=LR.fit(X_train,y_train)


#predicting the test label with LR. Predict always takes X as input
y_pred=LR.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0])